apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: task-app-ingress
spec:
  rules:
    - http:
        paths:
          - path: /v1/files
            backend:
              serviceName: file-upload-service
              servicePort: 8080
          - path: /v1/files/*
            backend:
              serviceName: file-upload-service
              servicePort: 8080
          - path: /v1/statistics
            backend:
              serviceName: statistics-service
              servicePort: 8082
          - path: /v1/statistics/*
            backend:
              serviceName: statistics-service
              servicePort: 8082
          - path: /api/v1/task
            backend:
              serviceName: task-management-service
              servicePort: 8083
          - path: /api/v1/task/*
            backend:
              serviceName: task-management-service
              servicePort: 8083
          - path: /api/v1/board
            backend:
              serviceName: task-management-service
              servicePort: 8083
          - path: /api/v1/board/*
            backend:
              serviceName: task-management-service
              servicePort: 8083
          - path: /api/v1/team
            backend:
              serviceName: team-management-service
              servicePort: 8084
          - path: /api/v1/team/*
            backend:
              serviceName: team-management-service
              servicePort: 8084
          - path: /api/v1/user
            backend:
              serviceName: team-management-service
              servicePort: 8084
          - path: /api/v1/user/*
            backend:
              serviceName: team-management-service
              servicePort: 8084
