apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statistics-service
  template:
    metadata:
      labels:
        app: statistics-service
    spec:
      containers:
        - image: zp8358/statisticsservice:1.0.0-SNAPSHOT-1.1
          resources:
            requests:
              cpu: "30m"
            limits:
              cpu: "50m"
          name: statistics-service
          env:
            - name: DBURL
              value: jdbc:postgresql://hattie.db.elephantsql.com:5432/wghpmtgy
            - name: DBUSERNAME
              value: wghpmtgy
            - name: DBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-pass-statistics
                  key: DBPASSWORD
                  #kubectl create secret generic db-pass-statistics --from-literal=DBPASSWORD=toJePassword
          ports:
            - containerPort: 8082
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/statistics/checks/health/liveness
              port: server
            initialDelaySeconds: 1800
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /v1/statistics/checks/health/readiness
              port: server
            initialDelaySeconds: 1800
            periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: statistics-service
spec:
  type: LoadBalancer
  ports:
    - port: 8082
      protocol: TCP
      targetPort: server
  selector:
    app: statistics-service